# CLMM Conda environment
name: clmm
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.10.2
  - pip>=21.0
  - jupyter>=1.0
  - numpy==1.25.2
  - scipy==1.11.2
  - astropy==5.3.2
  - healpy == 1.16.5
  - matplotlib==3.7.2
  - gsl==2.7
  - cmake==3.30.0
  - pyccl==3.0
  - numcosmo==0.18.2
  - pytest=7.4.0
  - sphinx==7.2.4
  - pip:
        - qp-prob @ git+https://github.com/LSSTDESC/qp.git
