name: Build and Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-gcc-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
    - name: Install prereq and NumCosmo using conda
      run: |
        echo "$CONDA/bin" >> $GITHUB_PATH
        conda install -c conda-forge gobject-introspection pygobject numcosmo cmake swig setuptools_scm sphinx sphinx_rtd_theme nbconvert pandoc ipython
    - name: Install prereq using pip
      run: |
        pip install -r requirements.txt
    - name: Install the package
      run: |
        pip install .
# temporarily moved up due to libarchive issue - see PR 620
#    - name: Install NumCosmo from conda-forge
#      run: |
#        conda install -c conda-forge numcosmo
    - name: Install cluster_toolkit from source
      run: |
        git clone https://github.com/tmcclintock/cluster_toolkit.git
        cd cluster_toolkit
        pip install .
    - name: Install CCL from source
      run: |
        # temporarily moved up due to libarchive issue - see PR 620
        #conda install -c conda-forge cmake swig setuptools_scm
        git clone https://github.com/LSSTDESC/CCL
        cd CCL
        pip install .
    - name: Run the unit tests
      run: |
        pip install pytest pytest-cov
        pytest tests/ --ignore=cluster_toolkit/tests --cov=clmm/
      env:
        DISPLAY: test
# temporarily moved up due to libarchive issue - see PR 620
#    - name: Install Sphinx prereq
#      run: |
#        conda install -c conda-forge sphinx sphinx_rtd_theme nbconvert pandoc ipython ipython_genutils
    - name: Analysing the code with pylint
      run: |
        pip install pylint
        pylint clmm --ignored-classes=astropy.units
    - name: Run the docs
      run: |
        make -C docs/ html
    - name: Coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pip install coveralls
        coveralls --service=github
